stages:
  - compile
  - test_ff
  - dump_ff

before_script:
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - export CI_HOME="$( pwd )"
  - git config --global user.name 'Homer Simpson' ## dummy name
  - git config --global user.email 'fake@mail.yes' ## does not
  - git config --global user.gitlab 'homerJay' ## matter
  - export CMSSW_GIT_REFERENCE="/cvmfs/cms.cern.ch/cmssw.git.daily"
  - export SCRAM_ARCH="slc7_amd64_gcc700"
  - export CMSSW_VERSION="CMSSW_10_2_14"
  - export CMS_PATH=/cvmfs/cms-ib.cern.ch/week0 #https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/blob/master/scripts/restore_cmssw.sh#L14
  - cd $CI_HOME
  - ls -al

compile:
  tags: [cvmfs]
  stage: compile
  script:
    - cd $CI_HOME/..
    - rm -Rf $CMSSW_VERSION
    - scramv1 project CMSSW $CMSSW_VERSION
    - ls -al
    - cd $CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    # - git cms-init
    - git cms-merge-topic cms-egamma:EgammaPostRecoTools
    - git cms-merge-topic cms-egamma:PhotonIDValueMapSpeedup1029
    - git cms-merge-topic cms-egamma:slava77-btvDictFix_10210
    - git cms-addpkg EgammaAnalysis/ElectronTools
    - rm EgammaAnalysis/ElectronTools/data -rf
    - git clone https://github.com/cms-data/EgammaAnalysis-ElectronTools.git EgammaAnalysis/ElectronTools/data
    - cp -r $CI_HOME/../Firefighter $CMSSW_VERSION/src
    - scram b -j4
    - cd $CMSSW_BASE/..
    - tar -czf cmssw.tgz $CMSSW_VERSION
    - du -csh cmssw.tgz
    - mv $CI_HOME/../cmssw.tgz $CI_HOME
  artifacts:
    paths:
      - cmssw.tgz
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test_sigMC:
  tags: [cvmfs]
  stage: test_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - wget -nv http://wsi.web.cern.ch/wsi/public/gitlabCI/SIDM_4mu.root
    - cmsRun $CMSSW_BASE/src/Firefighter/ffConfig/cfg/ffNtupleFromAOD_v2_cfg.py config=$CMSSW_BASE/src/Firefighter/ffConfig/python/test/ffSuperConfig_GitLabCI_signal-4mu.yml
    - wget -nv http://wsi.web.cern.ch/wsi/public/gitlabCI/SIDM_2mu2e.root
    - cmsRun $CMSSW_BASE/src/Firefighter/ffConfig/cfg/ffNtupleFromAOD_v2_cfg.py config=$CMSSW_BASE/src/Firefighter/ffConfig/python/test/ffSuperConfig_GitLabCI_signal-2mu2e.yml
    - mv ffNtuple_signal-2mu2e.root $CI_HOME
    - mv ffNtuple_signal-4mu.root $CI_HOME
  artifacts:
    paths:
      - ffNtuple_signal-2mu2e.root
      - ffNtuple_signal-4mu.root

sigMC_dump:
  tags: [cvmfs]
  stage: dump_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - rootls -1t ffNtuple_signal-2mu2e.root:ffNtupleStat
    - rootls -1t ffNtuple_signal-2mu2e.root:ffNtuplizer
    - rootls -1t ffNtuple_signal-4mu.root:ffNtupleStat
    - rootls -1t ffNtuple_signal-4mu.root:ffNtuplizer

test_bkgMC:
  tags: [cvmfs]
  stage: test_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - wget -nv http://wsi.web.cern.ch/wsi/public/gitlabCI/ZZ_numEvent300.root
    - cmsRun $CMSSW_BASE/src/Firefighter/ffConfig/cfg/ffNtupleFromAOD_v2_cfg.py config=$CMSSW_BASE/src/Firefighter/ffConfig/python/test/ffSuperConfig_GitLabCI_ZZ.yml
    - mv ffNtuple_ZZ.root $CI_HOME
  artifacts:
    paths:
      - ffNtuple_ZZ.root

bkgMC_dump:
  tags: [cvmfs]
  stage: dump_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - rootls -1t ffNtuple_ZZ.root:ffNtupleStat
    - rootls -1t ffNtuple_ZZ.root:ffNtuplizer

test_bkgMC4Trg:
  tags: [cvmfs]
  stage: test_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - wget -nv http://wsi.web.cern.ch/wsi/public/gitlabCI/ZZ_numEvent300.root
    - cmsRun $CMSSW_BASE/src/Firefighter/ffConfig/cfg/ffNtupleFromAOD_trigger_cfg.py config=$CMSSW_BASE/src/Firefighter/ffConfig/python/test/ffSuperConfig_trigger_GitLabCI_ZZ.yml
    - mv ffNtuple_ZZ_trigger.root $CI_HOME
  artifacts:
    paths:
      - ffNtuple_ZZ_trigger.root

bkgMC4Trg_dump:
  tags: [cvmfs]
  stage: dump_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - rootls -1t ffNtuple_ZZ_trigger.root:ffNtupleStat
    - rootls -1t ffNtuple_ZZ_trigger.root:ffNtuplizer


test_data:
  tags: [cvmfs]
  stage: test_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - wget -nv http://wsi.web.cern.ch/wsi/public/gitlabCI/DoubleMuon2018C_numEvent300.root
    - cmsRun $CMSSW_BASE/src/Firefighter/ffConfig/cfg/ffNtupleFromAOD_v2_cfg.py config=$CMSSW_BASE/src/Firefighter/ffConfig/python/test/ffSuperConfig_GitLabCI_DoubleMuon2018C.yml
    - mv ffNtuple_DoubleMuon2018C.root $CI_HOME
  artifacts:
    paths:
      - ffNtuple_DoubleMuon2018C.root

data_dump:
  tags: [cvmfs]
  stage: dump_ff
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - rootls -1t ffNtuple_DoubleMuon2018C.root:ffNtupleStat
    - rootls -1t ffNtuple_DoubleMuon2018C.root:ffNtuplizer
