# all-in-one configuration file for Firefighter settings

job-spec:
  numThreads: 8
  reportEvery: 100

condition-spec:
  globalTag: "102X_upgrade2018_realistic_v19"

data-spec:
  inputFileList:
    - /store/group/lpcmetx/MCSIDM/AODSIM/2018/SIDM_XXTo2ATo2Mu2E/mXX-100_mA-5_lxy-0p3_ctau-0p375_AODSIM_2018/190720_214028/0000/SIDM_AODSIM_1.root
  maxEvents: 50
  outputFileName: "ffNtuple_signal-2mu2e_mXX-100_mA-5_lxy-0p3.root"
  lumiMask: ""
  dataType: "sigmc"

reco-spec:
  eventRegion: "all"
  leptonJetCandStrategy: "hadronFree"
