# all-in-one configuration file for Firefighter settings

job-spec:
  numThreads: 8
  reportEvery: 100

condition-spec:
  globalTag: "102X_upgrade2018_realistic_v19"

data-spec:
  inputFileList:
    - /store/group/lpcmetx/MCSIDM/AODSIM/2018/CRAB_PrivateMC/SIDM_BsTo2DpTo4Mu_MBs-100_MDp-5_ctau-375/181228_055526/0000/SIDM_AODSIM_1.root
  maxEvents: 50
  outputFileName: "ffNtuple_signal-4mu_mXX-100_mA-5_lxy-300.root"
  lumiMask: ""
  dataType: "sigmc"

reco-spec:
  eventRegion: "all"
  leptonJetCandStrategy: "hadronFree"
